site_name: Mastering Django
site_url: https://example.com/docs/
docs_dir: docs
site_dir: site
strict: false
theme:
  name: material
  font: 
    text: Merriweather
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: green
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - def_list
  - tables

plugins:
  - search

#--- navigation structure ---
nav:
  - Introduction: index.md
  - Django Basics:
      - Introduction to Django: unit-1/introduction-to-django.md
      - Virtual Environments: unit-1/virtual-environment.md
      - Setup a Project: unit-1/project-setup.md
      - Project and App Structure: unit-1/project-and-app-structure.md
  - Models and Databases:
      - Overview: unit-2/overview.md
      - Migrations: unit-2/database-migrations.md
      - Admin Interface: unit-2/admin-interface.md
      - Forms in Django: unit-2/forms-in-django.md
      - Database Setup: unit-2/database-setup.md
      - Environment Variables: unit-2/using-environment-variables.md
  - Views, URLConfs, Template Engine and Non-HTML Content:
      - Overview: unit-3/overview.md
      - Advanced URL Dispatching: unit-3/advanced-url-dispatching.md
      - Working with Generic Views: unit-3/working-with-generic-views.md
      - Deep Dive - Django Template System: unit-3/deep-dive-django-templates.md
      - Specialized Content & Output: unit-3/specialized-content-and-output.md
      - Metadata & Discovery Frameworks: unit-3/metadata-and-discovery-frameworks.md
  
  # - Users, caching and Subframework:
  #     - Overview: unit-4/overview.md

  # - Middleware, Legacy Databases and Admin Interface:
  #     - Overview: unit-5/overview.md
  # - Internationalization, Security and Deployment:
  #     - Overview: unit-6/overview.md
